version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: ./fastapi_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./fastapi_service:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - redis
      - mongo

  model:
    build: ./model_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    env_file:
      - .env.dev

volumes:
  mongo_data:
