# version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db

  model-service:
    build: ./model-service
    container_name: model-service
    ports:
      - "50051:50051"
    env_file:
      - .env.dev
    depends_on:
      - mongo

  msa-ai-service:
    build: ./msa-ai-service
    container_name: msa-ai-service
    ports:
      - "8000:8000"
    volumes:
      - ./msa-ai-service/app:/app/app   # 코드 핫리로드용 (개발시)
    env_file:
      - .env.dev
    depends_on:
      - redis
      - mongo
      - model-service

volumes:
  mongo_data:
